// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package labx_subs

type AccessInput struct {
	Name     string  `json:"name"`
	Supplier string  `json:"supplier"`
	URL      *string `json:"url"`
	User     *string `json:"user"`
}

type SupplierInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}
